#!/bin/bash
if [ $# -ne 1 ]
then
  echo "one integer is needed"
  exit 2
fi

if [ $1 -lt 2 -o $1 -gt 10 ]
then
  echo "integer between 2 and 10"
  echo 2
fi

xcount=1
ycount=$1

while [[ $ycount -gt 0 ]]
do
  while [[ $xcount -le $1 ]]
  do
    if [ $xcount -eq 1 -o $xcount -eq $1 ]
    then
    if [ $ycount -eq 1 -o $ycount -eq $1 ]
      then
        echo -n "@"
      else
	echo -n "&"
    fi
    else
      if [ $ycount -eq 1 -o $ycount -eq $1 ]
      then
        echo -n "+"
      else
         echo -n " "
      fi
    fi
    xcount=$(($xcount+1))
  done
  xcount=1
  ycount=$(($ycount-1))
  echo " "
done


